package chapter10;

import java.util.Scanner;

public class ExceptionTryCatchTest {

	
	Scanner ac = new Scanner(System.in);
	
	System.out.println("숫자 1을 입력하세요>> ");
int num1 = sc.nextInt();


System.out.println("숫자 2를 입력하세요 >>");
int num2 = sc.nextInt();
	

try {
System.out.println("num1/num2 = " + num1/num2);   // <= 예외가 발생할 수 있는 
String str = null;

System.out.println(str.length());

} catch(Exception e) {
System.out.println("0으로 나누는 것은 불가합니다.");
e.print

}
	


}
